version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tickether

  testrpc:
    image: testrpc
    ports:
      - "8545:8545"

  db:
    image: db
    ports:
      - "3004:3004"
    links:
      - postgres
    environment:
      DATABASEUSER: docker
      DATABASEPASSWORD: docker
      DATABASEADDRESS: postgres
      DATABASEPORT: 5432
    depends_on:
      - postgres

  eth:
    image: eth
    ports:
      - "3002:3002"
    links:
      - db
      - testrpc
    depends_on:
      - db
      - testrpc
    environment:
      ETHEREUM_CONNECTION_STRING: http://testrpc:8545
      DB_SERVER_URL: http://db


  auth:
    image: auth
    ports:
      - "3003:3003"
    links:
      - db
    depends_on:
      - db
    environment:
      DB_SERVER_URL: http://db
